In [1]:
import numpy as np
import pandas as pd
import sklearn.metrics

In [2]:
both_gen = pd.read_csv('biostamp_thigh_chest_rf15_Ellis_clean_complete.csv')

In [7]:
both_gen_accuracies = sklearn.metrics.precision_recall_fscore_support(both_gen['general_coding'], both_gen['predicted'], labels=['sit', 'standing', 'walk/run', 'riding in vehicle', 'other'])
both_gen_accuracies

(array([0.97883533, 0.89604486, 0.89794648, 0.        , 0.97419805]),
 array([0.98421951, 0.94797595, 0.82910188, 0.        , 0.69341496]),
 array([0.98152004, 0.92127916, 0.86215202, 0.        , 0.81016818]),
 array([170527, 112275,  55694,   1520,   6044]))

In [4]:
wrist_gen = pd.read_csv('actigraph_wrist23_rf15_Ellis_clean_wrist_complete.csv')

In [8]:
wrist_gen_accuracies = sklearn.metrics.precision_recall_fscore_support(wrist_gen['Ellis_coding'], wrist_gen['predicted'], labels=['sit', 'standing', 'walk/run', 'riding in vehicle', 'other'])
wrist_gen_accuracies

(array([0.75599688, 0.53316739, 0.86959596, 0.        , 0.        ]),
 array([0.78722944, 0.6068456 , 0.64128246, 0.        , 0.        ]),
 array([0.77129711, 0.56762561, 0.73818863, 0.        , 0.        ]),
 array([170987, 108011,  55612,   1520,   6044]))

In [9]:
bio_fullRF = pd.read_csv('biostamp_thigh_chest_rf15_full_clean_complete.csv')

In [10]:
full_labels = ['SB- lying',
          'SB-sitting',
          'LA- stand',
          'LA- stand and move light',
          'LA- stand and move moderate',
          'LA- stand and move vigorous',
          'WA- walk light',
          'WA- walk moderate',
          'WA- walk vigorous',
          'WA- ascend stairs',
          'WA- descend stairs',
          'WA- running',
          'SP- other sport movement',
          'SP- bike']

bio_fullRF_accuracies = sklearn.metrics.precision_recall_fscore_support(bio_fullRF['posture_coding'], 
                                                                       bio_fullRF['predicted'],
                                                                       labels=full_labels)

/Users/samhsu/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [11]:
bio_fullRF_accuracies

(array([0.        , 0.98626489, 0.80347954, 0.365322  , 0.03398058,
        0.        , 0.2731779 , 0.74426909, 0.        , 0.37078652,
        0.43315508, 0.96004052, 0.        , 0.96850225]),
 array([0.        , 0.98408001, 0.92012132, 0.29390872, 0.00637329,
        0.        , 0.15349701, 0.83422444, 0.        , 0.23571429,
        0.07964602, 0.92787206, 0.        , 0.74809666]),
 array([0.        , 0.98517124, 0.85785367, 0.32574732, 0.01073345,
        0.        , 0.19655241, 0.78668357, 0.        , 0.28820961,
        0.1345515 , 0.94368223, 0.        , 0.84414978]),
 array([    25, 171985,  86381,  22524,   3295,     78,   9694,  32731,
          1974,   1120,   1017,   9192,      2,   6042]))

In [12]:
bio_fullRF['posture_coding'].value_counts()

SB-sitting                     171985
LA- stand                       86381
WA- walk moderate               32731
LA- stand and move light        22524
WA- walk light                   9694
WA- running                      9192
SP- bike                         6042
LA- stand and move moderate      3295
WA- walk vigorous                1974
WA- ascend stairs                1120
WA- descend stairs               1017
LA- stand and move vigorous        78
SB- lying                          25
SP- other sport movement            2
Name: posture_coding, dtype: int64

In [13]:
bio_fullRF['posture_coding'].value_counts()/bio_fullRF.shape[0]

SB-sitting                     0.496980
LA- stand                      0.249613
WA- walk moderate              0.094582
LA- stand and move light       0.065087
WA- walk light                 0.028012
WA- running                    0.026562
SP- bike                       0.017459
LA- stand and move moderate    0.009521
WA- walk vigorous              0.005704
WA- ascend stairs              0.003236
WA- descend stairs             0.002939
LA- stand and move vigorous    0.000225
SB- lying                      0.000072
SP- other sport movement       0.000006
Name: posture_coding, dtype: float64